config {
    ...issko_config.settings.lslog
}

/* COBOL MAPPING:
   In COBOL, this was a specific "Read LSLOGV0" triggered only when 
   the Store Number (NUMSTO) changed in the main loop.
   
   SQL Logic:
   We simply prepare this as a View. In the main step, we will LEFT JOIN 
   this to the main stock data to attach the Product (CODPRD) and Housing (CODLGT) codes.
*/

SELECT 
    lslog_codsoc AS codsoc,
    lslog_numsto AS numsto,
    lslog_codlgt AS codlgt,       -- Housing Code
    lslog_codlsc AS codprd        -- Product Code (Mapped from CODLSC)

FROM ${ref("LSLOG")}